name: "Slack Notification"
description: "Send a templated Slack notification after a GitHub Actions job"
inputs:
  template_file:
    required: false
    default: "default-payload.json"
    description: "Name of the avaliable template file."
  status:
    required: true
    description: "The job status (success/failure)"
  method:
    required: true
    description: "The Slack API method to call."
  token:
    required: true
    description: "Slack bot token"
  channel_id:
    required: true
    description: "Slack channel ID"
  run_id:
    required: false
    default: "${{ github.run_id }}"
    description: "GitHub Actions run ID"
  api:
    required: false
    description: "A custom API URL to send Slack API method requests to."
  errors:
    required: false
    default: "false"
    description: "If the step exits with an error on errors or continues."
  payload:
    required: false
    description: "Attributes that create the content of the request using JSON or YAML."
  payload-delimiter:
    required: false
    description: "Field separator for nested attributes in the input payload."
  payload-file-path:
    required: false
    description: "Path to a file containing a valid input payload made of JSON or YAML."
  payload-templated:
    required: false
    default: "true"
    description: "If templated variables in input payloads should be replaced."
  proxy:
    required: false
    description: "An optional proxied route for HTTPS connections."
  retries:
    required: false
    default: "5"
    description: "The strategy to use when performing retried requests."
  webhook:
    required: false
    description: "A location for posting request payloads."
  webhook-type:
    required: false
    description: "Option to use either an incoming webhook or webhook trigger."

runs:
  using: "composite"
  steps:
    - name: Send Slack Message
      uses: hemupadhyay26/slack-github-action@main
      env:
        SLACK_COLOR: ${{ inputs.status == 'success' && '#36a64f' || '#FF0000' }}
        CHANNEL_ID: ${{ inputs.channel_id }}
        RUN_ID: ${{ inputs.run_id }}
        STATUS: ${{ inputs.status }}
      with:
        method: ${{ inputs.method }}
        token: ${{ inputs.token }}
        payload-file-path: ./.github/resources/.slack/${{ inputs.template_file }}
        payload-templated: ${{ inputs.payload-templated }}
        api: ${{ inputs.api }}
        proxy: ${{ inputs.proxy }}
        retries: ${{ inputs.retries }}
        webhook: ${{ inputs.webhook }}
        webhook-type: ${{ inputs.webhook-type }}
        errors: ${{ inputs.errors }}

    - name: Log Success Message
      if: success()
      shell: bash
      run: |
        echo "Slack notification sent successfully to channel"