name: "Slack Notification"
description: "Send a templated Slack notification after a GitHub Actions job"
inputs:
  status:
    required: true
    description: "The job status (success/failure)"
  method:
    required: true
    description: "The Slack API method to call."
  token:
    required: true
    description: "Slack bot token"
  run_number:
    required: true
    description: "GitHub Actions run ID"
  channel_id:
    required: true
    description: "Slack channel ID"
  api:
    required: false
    description: "A custom API URL to send Slack API method requests to."
  errors:
    required: false
    default: "false"
    description: "If the step exits with an error on errors or continues."
  payload:
    required: false
    description: "Attributes that create the content of the request using JSON or YAML."
  payload-delimiter:
    required: false
    description: "Field separator for nested attributes in the input payload."
  payload-file-path:
    required: false
    description: "Path to a file containing a valid input payload made of JSON or YAML."
  payload-templated:
    required: false
    default: "false"
    description: "If templated variables in input payloads should be replaced."
  proxy:
    required: false
    description: "An optional proxied route for HTTPS connections."
  retries:
    required: false
    default: "5"
    description: "The strategy to use when performing retried requests."
  webhook:
    required: false
    description: "A location for posting request payloads."
  webhook-type:
    required: false
    description: "Option to use either an incoming webhook or webhook trigger."

runs:
  using: "composite"
  steps:
    - name: Set Slack color
      id: statusColor
      shell: bash
      run: ./src/set-color.sh "${{ inputs.status }}"

    - name: Send Slack Message
      uses: slackapi/slack-github-action@v2
      with:
        method: ${{ inputs.method }}
        token: ${{ inputs.token }}
        payload-templated: ${{ inputs.payload-templated }}
        payload-file-path: ${{ inputs.payload-file-path }}
        payload-delimiter: ${{ inputs.payload-delimiter }}
        api: ${{ inputs.api }}
        proxy: ${{ inputs.proxy }}
        retries: ${{ inputs.retries }}
        webhook: ${{ inputs.webhook }}
        webhook-type: ${{ inputs.webhook-type }}
        errors: ${{ inputs.errors }}
        payload: |
          {
            "channel": "${{ inputs.channel_id }}",
            "text": "Repository: ${{ github.server_url }}/${{ github.repository }}",
            "attachments": [
              {
                "color": "${{ steps.statusColor.outputs.color }}",
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      { "type": "mrkdwn", "text": "*Status:*\n${{ inputs.status }}" },
                      { "type": "mrkdwn", "text": "*Author:*\n${{ github.actor }}" },
                      { "type": "mrkdwn", "text": "*Branch:*\n${{ github.ref_name }}" }
                    ]
                  },
                  {
                    "type": "actions",
                    "elements": [
                      {
                        "type": "button",
                        "text": { "type": "plain_text", "emoji": true, "text": "View Logs" },
                        "style": "primary",
                        "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ inputs.run_number }}"
                      }
                    ]
                  }
                ]
              }
            ]
          }

    - name: Log Success Message
      if: success()
      shell: bash
      run: |
        echo "Slack notification sent successfully to channel"