name: Slack Notification Test

on:
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  slack-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Slack Action Dynamic Workflow result
        uses: ./
        with:
          status: ${{ job.status }}
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          run_number: ${{ github.run_id }} 
          channel_id: ${{ vars.SLACK_CHANNEL_ID }}

      - name: Run Slack Action for Failure
        uses: ./
        with:
          status: failure
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          run_number: ${{ github.run_id }} 
          channel_id: ${{ vars.SLACK_CHANNEL_ID }}

      - name: Run Slack Action for Success
        uses: ./
        with:
          status: success
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          run_number: ${{ github.run_id }} 
          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
