name: Slack Notification Test

on:
  push: 
    branches:
      - main
      - next
  workflow_dispatch:

jobs:
  slack-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Reveal contents of the github payload
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}

      - name: Run Slack Action Dynamic Workflow result
        uses: ./
        with:
          template_file: default-payload.json
          status: ${{ job.status }}
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
          payload-templated: true
          errors: true

      - name: Run Slack Action for Failure
        uses: ./
        with:
          status: failure
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
          errors: true

      - name: Run Slack Action for Success without Templating
        uses: ./
        with:
          status: success
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          run_id: ${{ github.run_id }} 
          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
