name: Slack Notification Test

on:
  push: 
    branches:
      - main
      - next
  workflow_dispatch:

jobs:
  test-plain-text-payload:
    name: Test Plain Text Payload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Slack Action with Plain Text Payload
        uses: ./
        with:
          template_name: plain-text-payload.json
          status: ${{ job.status }}
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
          errors: true

  test-default-payload:
    name: Test Default Payload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Slack Action for Failure
        uses: ./
        with:
          status: failure
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          run_id: ${{ github.run_id }}
          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
          errors: true

      - name: Run Slack Action for Success
        uses: ./
        with:
          status: success
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          run_id: ${{ github.run_id }} 
          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
          errors: true
  test-detail-payload:
    name: Test Detail Payload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Slack Action with detail-payload
        uses: ./
        with:
          status: ${{ job.status }}
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          run_id: ${{ github.run_id }}
          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
          template_name: detail-payload.json
          errors: true

      
